#!/usr/bin/env bash
#
# mayhem/build.sh — build Verilator's fuzz targets + a clean test build.
#
# Runs inside the commit image (mayhem/Dockerfile) as `mayhem` in /mayhem. The base image
# (ghcr.io/mayhemheroes/base) exports the build contract: CC/CXX, LIB_FUZZING_ENGINE,
# SANITIZER_FLAGS (ASan+UBSan, halting), DEBUG_FLAGS (-g -gdwarf-3), STANDALONE_FUZZ_MAIN, SRC.
#
# Targets produced:
#   /mayhem/verilator_bin              the Verilator front-end, sanitized (oracle + exec target)
#   /mayhem/verilator_fuzz             file-input launcher (open+exec; Mayhem smoketest compat)
#   /mayhem/fuzz_VL_DBG_MSGF           libFuzzer harness over the Verilated runtime formatter
#   /mayhem/fuzz_VL_DBG_MSGF-standalone   run-once reproducer for the harness
#   /mayhem/verilator_bin_test         a clean (non-sanitized) front-end for the test oracle
#
# Everything is ADDITIVE: upstream files are untouched; all outputs land under /mayhem.
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' (empty) — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# `=` (not `:=`) on SANITIZER_FLAGS: an explicit empty --build-arg SANITIZER_FLAGS= is honored
# (natural-crash build with no sanitizer runtime). The rest default on empty too.
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${MAYHEM_JOBS:=$(nproc)}"
: "${COVERAGE_FLAGS=}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE MAYHEM_JOBS COVERAGE_FLAGS
# In-tree build: verilator_bin's baked DEFENV points at /usr/local/share/verilator; override
# so re-runs (incl. air-gapped PATCH tier) find include/verilated_std.* under $SRC.
export VERILATOR_ROOT="$SRC"

cd "$SRC"

# Idempotent re-run (PATCH tier): the prior build leaves a sanitized obj_opt tree; start clean
# so the test-oracle configure/link never mixes unsanitized flags with ASan/UBSan objects.
make distclean >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 1) TEST-oracle build FIRST (clean, project-normal flags), stashed before we
#    reconfigure for the sanitized build. Build ONLY the optimized front-end
#    (`-C src opt`) — the dbg/coverage variants are not needed. Shared tree →
#    build, stash, distclean.
# ---------------------------------------------------------------------------
autoconf
env -u CFLAGS -u CXXFLAGS -u LDFLAGS ./configure
make -C src opt -j"$MAYHEM_JOBS"
# Stash outside $SRC: top-level `make distclean` removes verilator_bin* in the repo root.
cp bin/verilator_bin /tmp/verilator_bin_test
# Regenerated by the next configure; clear the object build so the sanitized reconfigure is clean.
make distclean >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 2) SANITIZED front-end build (the fuzzed program is instrumented + DWARF<4).
#    Use verilator's first-class --enable-dev-asan (which turns OFF tcmalloc/jemalloc
#    — mandatory for a clean ASan build) and, on top of it, thread the FULL contract
#    flags through configure's CXXFLAGS/LDFLAGS (they append via `+=` to every compile
#    incl. the PCH, and the final link): this adds UBSan, the halting off-switch and
#    DWARF<4 that --enable-dev-asan alone does not provide. An empty $SANITIZER_FLAGS
#    (natural-crash build) still gets DWARF symbols from $DEBUG_FLAGS.
# ---------------------------------------------------------------------------
autoconf
./configure --enable-dev-asan \
    CXXFLAGS="$SANITIZER_FLAGS $DEBUG_FLAGS" \
    LDFLAGS="$SANITIZER_FLAGS"
make -C src opt -j"$MAYHEM_JOBS"
cp bin/verilator_bin /mayhem/verilator_bin

# File-input launcher: explicit open() of @@ for Mayhem smoketest, then exec the sanitized binary.
$CXX -std=c++17 $SANITIZER_FLAGS $DEBUG_FLAGS "$SRC/mayhem/verilator_fuzz.cpp" \
    -o /mayhem/verilator_fuzz

# ---------------------------------------------------------------------------
# 3) libFuzzer harness over the Verilated runtime (include/verilated.cpp defines
#    VL_DBG_MSGF → _vl_string_vprintf, the fuzzed format-string parser). Compile the
#    runtime translation units the harness pulls in, sanitized, and link.
#    verilated_config.h was generated by configure in step 2.
# ---------------------------------------------------------------------------
VL_INC="-I$SRC/include -I$SRC/include/vltstd -I$SRC/src"
VL_RUNTIME_SRCS=(
  "$SRC/include/verilated.cpp"
  "$SRC/include/verilated_threads.cpp"
)
VLDEFS="-DVL_DEBUG=1 -DVM_TRACE=0 -DVM_COVERAGE=0 -DVM_SC=0"

# fuzzer binary
$CXX -std=c++17 $SANITIZER_FLAGS $DEBUG_FLAGS $LIB_FUZZING_ENGINE $VLDEFS $VL_INC \
    "$SRC/mayhem/fuzz_VL_DBG_MSGF.cpp" "${VL_RUNTIME_SRCS[@]}" \
    -lpthread -o /mayhem/fuzz_VL_DBG_MSGF

# standalone reproducer: compile the LLVM run-once driver as a C object first (clang++ would
# mangle its LLVMFuzzerTestOneInput ref), then link with the harness (no libFuzzer runtime).
$CC $SANITIZER_FLAGS $DEBUG_FLAGS -c "$STANDALONE_FUZZ_MAIN" -o /tmp/standalone_main.o
$CXX -std=c++17 $SANITIZER_FLAGS $DEBUG_FLAGS $VLDEFS $VL_INC \
    "$SRC/mayhem/fuzz_VL_DBG_MSGF.cpp" "${VL_RUNTIME_SRCS[@]}" /tmp/standalone_main.o \
    -lpthread -o /mayhem/fuzz_VL_DBG_MSGF-standalone

cp /tmp/verilator_bin_test /mayhem/verilator_bin_test

echo "build.sh: done"
ls -l /mayhem/verilator_bin /mayhem/verilator_fuzz /mayhem/verilator_bin_test /mayhem/fuzz_VL_DBG_MSGF /mayhem/fuzz_VL_DBG_MSGF-standalone
